[build]
  command = "chmod +x netlify-build.sh && ./netlify-build.sh"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--production=false"
  # These will be overridden by Netlify environment variables
  NEXT_PUBLIC_SUPABASE_URL = "https://tyorydcmacaqmdgfclas.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "sb_publishable_Kk0Flz-zLGxh1_t2uqFn8w_tDbngWwY"

# Headers for static assets
[[headers]]
  for = "/img/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"