[build]
  command = "chmod +x build.sh && ./build.sh"
  publish = ".next"
  functions = ".netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--production=false"
  DATABASE_URL = "file:./production.db"

# Next.js API Routes handling
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/___next_api_handler_*"
  status = 200

# Fallback untuk semua routes lainnya
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200