[build]
  command = "npm run build:netlify"
  publish = ".next"
  functions = "dist"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--production=false"
  DB_HOST = "localhost"
  DB_PORT = "3306"
  DB_USERNAME = "root"
  DB_PASSWORD = ""
  DB_DATABASE = "jsr_database"

# API Routes redirect to NestJS functions
[[redirects]]
  from = "/client-form"
  to = "/.netlify/functions/client-form"
  status = 200

[[redirects]]
  from = "/admin/*"
  to = "/.netlify/functions/admin"
  status = 200

# Fallback untuk semua routes lainnya
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200