[build]
  command = "next build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--production=false"

# Simple fallback for Next.js routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200