[build]
  command = "npx prisma generate && npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--production=false"

# Redirect untuk API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/__next_api_handler"
  status = 200